spring:
  datasource:
    url: jdbc:h2:mem:testdb # ??? ?? ??
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true # H2 ?? ???
      path: /h2-console
  data:
    redis:
      host: 172.17.129.27 # wsl ?? ??? ?? ?? localhost ? ?????
      port: 6379
      username: default
      password:

  # ?? ??
  cache:
    type: redis